import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { StoryService } from '../../../services/story';

@Component({
  selector: 'app-my-profile',
  templateUrl: './my-profile.component.html',
  styleUrls: ['./my-profile.component.css']
})
export class MyProfileComponent implements OnInit {
	uid: string; //user's id from local storage
	storyKey: any; //the key generated by firebase for each item
	story: object; //the story the user clicked on
	imgUrl: object[] = []; //store a list of image urls for this story

  constructor(private storyService: StoryService,
  						private routeParams: ActivatedRoute) { 
  	this.uid = JSON.parse(localStorage.getItem('currentUser')).uid;

  	let currentStory = this.routeParams.params.subscribe((data) => {
			this.storyKey = data.key;
  	});
  }

  ngOnInit() {
  	this.storyService.getStory(this.uid, this.storyKey).subscribe((story) => {
  		this.story = story
  		console.log(this.story); 		
  	})
  	this.storyService.getUrl(this.uid, this.storyKey).subscribe((storyImages) => {
  		console.log(storyImages);
  		this.imgUrl = storyImages;
  	})
  }

}
