import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, NavigationExtras } from '@angular/router';
import { StoryService } from '../../../services/story';

@Component({
  selector: 'app-my-profile',
  templateUrl: './my-profile.component.html',
  styleUrls: ['./my-profile.component.css']
})
export class MyProfileComponent implements OnInit {
	uid: string; //user's id from local storage
	storyKey: any; //the key generated by firebase for each item
	story; //the story the user clicked on
	imgUrl = []; //store a list of image urls for this story
  singularPlural: string = 'photo';

  constructor(private storyService: StoryService,
  						private routeParams: ActivatedRoute,
              private router: Router) { 
  	this.uid = JSON.parse(localStorage.getItem('currentUser')).uid;

  	let currentStory = this.routeParams.params.subscribe((data) => {
		  this.storyKey = data.key;
  	});
  }

  ngOnInit() {
  	this.storyService.getStory(this.uid, this.storyKey).subscribe((story) => {
  		this.story = story;		
  	});
  	this.storyService.getUrl(this.uid, this.storyKey).subscribe((storyImages) => {
  	
  		this.imgUrl = storyImages;
      if(this.imgUrl.length >= 5) {
        this.singularPlural = 'photos';
      }
  	});
  }

  morePhotos() {
    // let urlArray = this.imgUrl.slice(3);
  
    // let navigationExtras: NavigationExtras = {
    //         queryParams: {}      
    // }

    // urlArray.forEach((url, i) => {
    //   navigationExtras.queryParams[i] = url['url'];
    // });
    
      this.router.navigate(['my-profile-pics', {storyKey: this.storyKey}]);
  }

  viewSingleImage(img) {
    let navigationExtras: NavigationExtras = {
            queryParams: {
              url: img.url,
              key: img.$key,
              name: img.raw,
              storyKey: this.storyKey
            }
        };
   
    this.router.navigate(['single-img'], navigationExtras)
  }

}
